<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>81d6ef36-fd7d-482f-a485-b892c2d8f207</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstracciones\Abstracciones.csproj" />
    <ProjectReference Include="..\DA\DA.csproj" />
    <ProjectReference Include="..\Flujo\Flujo.csproj" />
  </ItemGroup>

</Project>
